import { supabase } from '@/integrations/supabase/client';
import type { DataSource, DetectedColumn, ColumnMapping } from '@/types/dataConnector';

// ---------------------------------------------------------------------------
// DB row shape (snake_case — matches Supabase columns)
// ---------------------------------------------------------------------------

interface DataSourceDbRow {
  id: string;
  name: string;
  connector_type: string;
  file_name: string;
  file_size_bytes: number;
  row_count: number;
  column_count: number;
  date_range_start: string | null;
  date_range_end: string | null;
  quality_score: number;
  schema_detected: DetectedColumn[];
  status: string;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Mappers
// ---------------------------------------------------------------------------

function dataSourceFromDbRow(row: DataSourceDbRow): DataSource {
  return {
    id: row.id,
    name: row.name,
    fileName: row.file_name,
    fileSize: row.file_size_bytes,
    rowCount: row.row_count,
    columnCount: row.column_count,
    dateRange:
      row.date_range_start && row.date_range_end
        ? { start: row.date_range_start, end: row.date_range_end }
        : undefined,
    qualityScore: row.quality_score,
    uploadedAt: row.created_at,
    status: row.status as DataSource['status'],
    schema: {
      columns: row.schema_detected,
      rowCount: row.row_count,
      columnCount: row.column_count,
      dateRange:
        row.date_range_start && row.date_range_end
          ? { start: row.date_range_start, end: row.date_range_end }
          : undefined,
    },
    connectorType: 'csv',
  };
}

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

/**
 * Fetch all data sources, ordered by most recent first.
 */
export async function fetchDataSources(): Promise<DataSource[]> {
  const { data, error } = await supabase
    .from('data_sources')
    .select('*')
    .order('created_at', { ascending: false });

  if (error) throw new Error(`Failed to fetch data sources: ${error.message}`);
  return (data || []).map((row) => dataSourceFromDbRow(row as unknown as DataSourceDbRow));
}

/**
 * Create a data source (metadata) and insert all row data in batches.
 *
 * @param source  DataSource metadata (id will be generated by Supabase)
 * @param rows    Array of { header: value } objects — the actual CSV data
 * @returns       The Supabase-generated UUID for the new data source
 */
export async function createDataSource(
  source: Omit<DataSource, 'id' | 'uploadedAt'>,
  rows: Record<string, string>[],
): Promise<string> {
  // 1. Insert metadata into data_sources
  const { data, error } = await supabase
    .from('data_sources')
    .insert({
      name: source.name,
      connector_type: source.connectorType,
      file_name: source.fileName,
      file_size_bytes: source.fileSize,
      row_count: source.rowCount,
      column_count: source.columnCount,
      date_range_start: source.dateRange?.start ?? null,
      date_range_end: source.dateRange?.end ?? null,
      quality_score: source.qualityScore,
      schema_detected: source.schema.columns,
      status: source.status,
    })
    .select('id')
    .single();

  if (error) throw new Error(`Failed to create data source: ${error.message}`);

  const dataSourceId = data.id as string;

  // 2. Batch-insert row data into data_uploads (chunks of 500)
  const BATCH_SIZE = 500;
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE).map((row, batchIndex) => ({
      data_source_id: dataSourceId,
      row_data: row,
      row_index: i + batchIndex,
    }));

    const { error: batchError } = await supabase
      .from('data_uploads')
      .insert(batch);

    if (batchError) {
      // Clean up the data source if row insertion fails
      await supabase.from('data_sources').delete().eq('id', dataSourceId);
      throw new Error(`Failed to insert row data (batch ${Math.floor(i / BATCH_SIZE) + 1}): ${batchError.message}`);
    }
  }

  return dataSourceId;
}

/**
 * Create a data source and insert typed rows directly into a target fact/dim table.
 *
 * @param source        DataSource metadata + targetTable + columnMappings
 * @param rows          Array of type-coerced objects with target column names as keys
 * @returns             The Supabase-generated UUID for the new data source
 */
export async function createDataSourceWithTargetTable(
  source: Omit<DataSource, 'id' | 'uploadedAt'> & {
    targetTable: string;
    columnMappings: ColumnMapping[];
  },
  rows: Record<string, unknown>[],
): Promise<string> {
  // 1. Insert metadata into data_sources (with target_table + column_mappings)
  const { data, error } = await supabase
    .from('data_sources')
    .insert({
      name: source.name,
      connector_type: source.connectorType,
      file_name: source.fileName,
      file_size_bytes: source.fileSize,
      row_count: source.rowCount,
      column_count: source.columnCount,
      date_range_start: source.dateRange?.start ?? null,
      date_range_end: source.dateRange?.end ?? null,
      quality_score: source.qualityScore,
      schema_detected: source.schema.columns,
      status: source.status,
      target_table: source.targetTable,
      column_mappings: source.columnMappings,
    })
    .select('id')
    .single();

  if (error) throw new Error(`Failed to create data source: ${error.message}`);

  const dataSourceId = data.id as string;

  // 2. Batch-insert typed rows into the TARGET table (not data_uploads)
  const BATCH_SIZE = 500;
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);

    const { error: batchError } = await supabase
      .from(source.targetTable)
      .insert(batch);

    if (batchError) {
      // Mark data_sources as error (don't delete — helps debugging)
      await supabase
        .from('data_sources')
        .update({ status: 'error' })
        .eq('id', dataSourceId);

      throw new Error(
        `Failed to insert into ${source.targetTable} (batch ${Math.floor(i / BATCH_SIZE) + 1}): ${batchError.message}`,
      );
    }
  }

  return dataSourceId;
}

/**
 * Delete a data source and all its uploaded rows (cascade).
 */
export async function deleteDataSource(id: string): Promise<void> {
  const { error } = await supabase
    .from('data_sources')
    .delete()
    .eq('id', id);

  if (error) throw new Error(`Failed to delete data source: ${error.message}`);
}
